#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("target_env")
target_env: Environment
sources = [
    target_env.File("CppLanguageSupport.cpp"),
    target_env.File("Logging.cpp"),
    target_env.File("Memory.cpp"),
    target_env.File("Stream.cpp"),
    target_env.File("String.cpp"),
    target_env.File("Utility.cpp"),
    target_env.File("Module/EventHook.cpp"),
    target_env.File("Module/FrameBuffer.cpp"),
    target_env.File("Module/Subsystem.cpp"),
]
KRE = target_env.StaticLibrary("KRE.o", target_env.Object(sources))
Export("KRE")
