#   Copyright 2026 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

from pathlib import Path

Import("build_env")
build_env: Environment
arch = build_env["arch"]
sources = [
    build_env.File("CRL/CRL.cpp"),
    build_env.File("Threading/InterruptLock.cpp"),
    build_env.File("Threading/Spinlock.cpp"),
    build_env.File("System/EventHook.cpp"),
    build_env.File("System/FrameBuffer.cpp"),
    build_env.File("System/Module.cpp"),
    build_env.File("System/Plugin.cpp"),
    build_env.File("Logging.cpp"),
    build_env.File("Memory.cpp"),
    build_env.File("Stream.cpp"),
    build_env.File("String.cpp"),
    build_env.File("Utility.cpp"),

]

build_env.SConscript(
    str(Path("HAL") / arch / "SConscript"),
    duplicate=0,
)
Import("HAL_SOURCES_KRE")
sources += HAL_SOURCES_KRE

KRE = build_env.StaticLibrary("KRE.o", build_env.Object(sources))
Export("KRE")
