#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("target_env")
target_env: Environment
sources = [
    target_env.File("AppBundle.cpp"),
    target_env.File("Bundle.cpp"),
    target_env.File("Definition.cpp"),
    target_env.File("KernelGuardian.cpp"),
    target_env.File("MemoryBundle.cpp"),
    target_env.File("SystemCallSubsystem.cpp"),
    target_env.File("ThreadingBundle.cpp"),
    target_env.File("VFSBundle.cpp"),
]
SystemCall = target_env.StaticLibrary("SystemCall.o", target_env.Object(sources))
Export("SystemCall")
