#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
sources = [
    build_env.File("AppBits.cpp"),
    build_env.File("Ember.cpp"),
    build_env.File("Enum.cpp"),
    build_env.File("MemoryBits.cpp"),
    build_env.File("SystemCallID.cpp"),
    build_env.File("VFSBits.cpp"),
]
Ember = build_env.StaticLibrary("Ember.o", build_env.Object(sources))
Export("Ember")
