#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(__file__)))

from typing import Any
from pathlib import Path
from Config import BuildConfig

import Build


class KernelBuildStep(Build.BuildStep):
    def name(self) -> str:
        """
        :return: Name of the build step.
        """

        return "Kernel Build"

    def execute(self, build_conf: dict[str, Any]) -> bool:
        """Execute this build step.
        :return: True: The build step was successful, False: Otherwise.
        """

        project_root = Path(build_conf[BuildConfig.PROJECT_ROOT.to_yaml_key()])
        kernel_directory = project_root / "Kernel"
        build_variables = [
            BuildConfig.BUILD,
            BuildConfig.ARCH,
            BuildConfig.QEMU_HOST,
            BuildConfig.SYSTEM_LOADER,
            BuildConfig.C,
            BuildConfig.CPP,
            BuildConfig.CRT_BEGIN,
            BuildConfig.CRT_END,
        ]
        with open(kernel_directory / "BuildVariables.py", "w") as file:
            file.writelines(["#\n", "# This file was automatically generated by Brokk.\n", "#\n"])
            for build_var in build_variables:
                file.write(
                    f"{build_var.to_scons_key()} = '{build_conf[build_var.to_yaml_key()]}'\n"
                )
        build_kernel_cmd = ["scons"]
        if not Build.exec_shell_cmd(build_kernel_cmd, str(kernel_directory)):
            return False

        arch = build_conf[BuildConfig.ARCH.to_yaml_key()]
        build = build_conf[BuildConfig.BUILD.to_yaml_key()]
        compilation_database = (project_root
                                / "Kernel"
                                / "Build"
                                / f"{arch}-{build}"
                                / "compile_commands.json")
        return Build.post_process_compilation_database(str(compilation_database), Path(""), False)
