#   Copyright 2026 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
sources = [
    build_env.File("ACPI/ACPI.cpp"),
    build_env.File("ACPI/ACPICA/CLibFunctions.cpp"),
    build_env.File("ACPI/ACPICA/osl.c"),
    build_env.File("ACPI/ACPICA/osl-to-rune-bridge.cpp"),
    build_env.File("Keyboard/HIDKeyboard.cpp"),
    build_env.File("Keyboard/PS2Keyboard.cpp"),
    build_env.File("MassStorage/AHCI/FIS.cpp"),
    build_env.File("MassStorage/AHCI/GPT.cpp"),
    build_env.File("MassStorage/AHCI/HostBusAdapterDriver.cpp"),
    build_env.File("MassStorage/AHCI/Port.cpp"),
    build_env.File("MassStorage/AHCI/PortDriver.cpp"),
    build_env.File("MassStorage/AHCI/PortEngine.cpp"),
    build_env.File("MassStorage/MassStorage.cpp"),
    build_env.File("PCI/ClassCode.cpp"),
    build_env.File("PCI/PCI.cpp"),
    build_env.File("PCI/Types.cpp"),
    build_env.File("PCI/VendorDB.cpp"),
    build_env.File("USB/ClassCode.cpp"),
    build_env.File("USB/Descriptor.cpp"),
    build_env.File("USB/Request.cpp"),
    build_env.File("USB/USB.cpp"),
    build_env.File("USB/VendorDB.cpp"),
    build_env.File("USB/HID/HID.cpp"),
    build_env.File("USB/HID/ItemParser.cpp"),
    build_env.File("USB/HID/UsageTables.cpp"),
    build_env.File("USB/xHCI/DeviceContext.cpp"),
    build_env.File("USB/xHCI/ExtendedCapability.cpp"),
    build_env.File("USB/xHCI/RegisterInterface.cpp"),
    build_env.File("USB/xHCI/Ring.cpp"),
    build_env.File("USB/xHCI/TRB.cpp"),
    build_env.File("USB/xHCI/xHCI.cpp"),
    build_env.File("Device.cpp"),
    build_env.File("DeviceModule.cpp"),
    build_env.File("KeyEventBuffer.cpp"),
]
acpi_sources = (Glob("ACPI/ACPICA/dispatcher/*.c")
                + Glob("ACPI/ACPICA/events/*.c")
                + Glob("ACPI/ACPICA/executer/*.c")
                + Glob("ACPI/ACPICA/hardware/*.c")
                + Glob("ACPI/ACPICA/namespace/*.c")
                + Glob("ACPI/ACPICA/parser/*.c")
                + Glob("ACPI/ACPICA/resources/*.c")
                + Glob("ACPI/ACPICA/tables/*.c")
                + Glob("ACPI/ACPICA/utilities/*.c"))
sources += acpi_sources

Device = build_env.StaticLibrary("Device.o", build_env.Object(sources))
Export("Device")
