#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
sources = [
    target_env.File("ACPI/ACPI.cpp"),
    target_env.File("ACPI/ACPICA/CLibFunctions.cpp"),
    target_env.File("ACPI/ACPICA/osl.c"),
    target_env.File("ACPI/ACPICA/osl-to-rune-bridge.cpp"),
    target_env.File("AHCI/AHCI.cpp"),
    target_env.File("AHCI/FIS.cpp"),
    target_env.File("AHCI/GPT.cpp"),
    target_env.File("AHCI/Port.cpp"),
    target_env.File("AHCI/PortEngine.cpp"),
    target_env.File("Keyboard/Keyboard.cpp"),
    target_env.File("Keyboard/PS2Keyboard.cpp"),
    target_env.File("DeviceModule.cpp"),
    target_env.File("PCI.cpp"),
]
acpi_sources = (Glob("ACPI/ACPICA/dispatcher/*.c")
                + Glob("ACPI/ACPICA/events/*.c")
                + Glob("ACPI/ACPICA/executer/*.c")
                + Glob("ACPI/ACPICA/hardware/*.c")
                + Glob("ACPI/ACPICA/namespace/*.c")
                + Glob("ACPI/ACPICA/parser/*.c")
                + Glob("ACPI/ACPICA/resources/*.c")
                + Glob("ACPI/ACPICA/tables/*.c")
                + Glob("ACPI/ACPICA/utilities/*.c"))
sources += acpi_sources

Device = build_env.StaticLibrary("Device.o", build_env.Object(sources))
Export("Device")
