#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import('target_env')
target_env: Environment
sources = [
    target_env.File('DwLibAlloc11.cpp'),
    target_env.File('LibAlloc11.cpp'),
    target_env.File('RuntimeSupport.cpp'),
    target_env.File('Start.asm'),
]
Forge = target_env.StaticLibrary('Forge.o', target_env.Object(sources))
Export('Forge')

crti = target_env.Object(target_env.File('crti.asm'))
crtn = target_env.Object(target_env.File('crtn.asm'))
linker_script = target_env.File('Userspace.ld')
Export('linker_script')
Export('crti')
Export('crtn')

