#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
sources = [
    build_env.File("CPU.cpp"),
    build_env.File("CPUModule.cpp"),
    build_env.File("E9Stream.cpp"),
    build_env.File("Interrupt/8259PIC.cpp"),
    build_env.File("Threading/MultiLevelQueue.cpp"),
    build_env.File("Threading/Mutex.cpp"),
    build_env.File("Threading/Scheduler.cpp"),
    build_env.File("Time/DeltaQueue.cpp"),
    build_env.File("Time/PIT.cpp"),
    build_env.File("Time/Timer.cpp"),
]
CPU = build_env.StaticLibrary("CPU.o", build_env.Object(sources))
Export("CPU")
