#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import('target_env')
target_env: Environment
sources = [
    target_env.File('Shell/Action.cpp'),
    target_env.File('Shell/AST.cpp'),
    target_env.File('Shell/AutoCompletion.cpp'),
    target_env.File('Shell/BuiltInCommand.cpp'),
    target_env.File('Shell/Environment.cpp'),
    target_env.File('Shell/Interpreter.cpp'),
    target_env.File('Shell/Lexer.cpp'),
    target_env.File('Shell/Parser.cpp'),
    target_env.File('OS.cpp'),
    target_env.File('StdIO.cpp'),
]
runeOS = target_env.StaticLibrary('runeOS.o', target_env.Object(sources))
Export('runeOS')
