#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("target_env")
target_env: Environment
sources = [
    target_env.File("Boot/Bootstrap-a.asm"),
    target_env.File("CPU/Interrupt/IDT.cpp"),
    target_env.File("CPU/Interrupt/IDT-a.asm"),
    target_env.File("CPU/Interrupt/Interrupt.cpp"),
    target_env.File("CPU/Interrupt/Interrupt-a.asm"),
    target_env.File("CPU/Interrupt/ISR-a.asm"),
    target_env.File("CPU/Threading/Stack.cpp"),
    target_env.File("CPU/CPU.cpp"),
    target_env.File("CPU/CPU-a.asm"),
    target_env.File("CPU/CPUID.cpp"),
    target_env.File("CPU/CPUID-a.asm"),
    target_env.File("CPU/GDT.cpp"),
    target_env.File("CPU/GDT-a.asm"),
    target_env.File("CPU/IO-a.asm"),
    target_env.File("CPU/X64Core.cpp"),
    target_env.File("CPU/X64Core-a.asm"),
    target_env.File("Memory/Paging.cpp"),
    target_env.File("Memory/Paging-a.asm"),
    target_env.File("Memory/VirtualMemory.cpp"),
    target_env.File("SystemCall/SystemCall.cpp"),
    target_env.File("SystemCall/SystemCall-a.asm"),
]
Arch = target_env.StaticLibrary("Arch.o", target_env.Object(sources))
Export("Arch")

crti = target_env.Object(target_env.File("crti.asm"))
crtn = target_env.Object(target_env.File("crtn.asm"))
Export("crti")
Export("crtn")
