#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("target_env")
target_env: Environment
sources = [
    target_env.File("DirectoryStream.cpp"),
    target_env.File("FileStream.cpp"),
    target_env.File("Node.cpp"),
    target_env.File("Path.cpp"),
    target_env.File("Status.cpp"),
    target_env.File("VFSModule.cpp"),
    target_env.File("FAT/FAT.cpp"),
    target_env.File("FAT/FAT32Engine.cpp"),
    target_env.File("FAT/FATDirectoryIterator.cpp"),
    target_env.File("FAT/FATDriver.cpp"),
    target_env.File("FAT/FATNode.cpp"),
    target_env.File("FAT/FileEntryManager.cpp"),
    target_env.File("FAT/VolumeManager.cpp"),
]
VirtualFileSystem = target_env.StaticLibrary("VirtualFileSystem.o", target_env.Object(sources))
Export("VirtualFileSystem")
