#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
HAL_SOURCES_KRE = [
    build_env.File("Atomic-a.asm"),
    build_env.File("CPU-a.asm"),
    build_env.File("GlobalConstructor-a.asm"),
    build_env.File("IDT.cpp"),
    build_env.File("IDT-a.asm"),
    build_env.File("Interrupt.cpp"),
    build_env.File("Interrupt-a.asm"),
    build_env.File("ISR-a.asm"),
]

Export("HAL_SOURCES_KRE")

crti = build_env.Object(build_env.File("crti.asm"))
crtn = build_env.Object(build_env.File("crtn.asm"))
Export("crti")
Export("crtn")
