#   Copyright 2025 Ewogijk
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

from SCons.Environment import *

Import("build_env")
build_env: Environment
sources = [
    build_env.File("Heimdall/AssertionHandler.cpp"),
    build_env.File("Heimdall/ConsoleReporter.cpp"),
    build_env.File("Heimdall/Engine.cpp"),
    build_env.File("Heimdall/GnomeReporter.cpp"),
    build_env.File("Heimdall/JUnitReporter.cpp"),
    build_env.File("Heimdall/TestRunInfoReporter.cpp"),
    build_env.File("Heimdall/TestTracker.cpp"),
    build_env.File("UnitTest/hre/HRE.cpp"),
    build_env.File("UnitTest/hre/HString.cpp"),
    build_env.File("UnitTest/hre/JUnitTestList.cpp"),
    build_env.File("UnitTest/hre/JUnitTestSuiteList.cpp"),
    build_env.File("UnitTest/hre/OptionList.cpp"),
    build_env.File("UnitTest/hre/ReporterRegistry.cpp"),
    build_env.File("UnitTest/hre/TestList.cpp"),
    build_env.File("UnitTest/hre/TestTracker.cpp"),
    build_env.File("UnitTest/Runner.cpp"),
]
Heimdall = build_env.StaticLibrary("Heimdall.o", build_env.Object(sources))
Export("Heimdall")
